apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: h8r2vztbi-python 
  janus-idp.io/tekton: h8r2vztbi-python
  backstage.io/kubernetes-id: h8r2vztbi-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h8r2vztbi-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml