apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h8r2vztbi-python
  janus-idp.io/tekton: h8r2vztbi-python
  backstage.io/kubernetes-id: h8r2vztbi-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h8r2vztbi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
